### PR TITLE
Create build.bat

### PR DESCRIPTION
**Pull request by SpeederX**
Added this, since if you're using windows, you just have to execute the commands which are the same but with a .bat file

### CODE REVIEW

**Comment by Yarflam** [comment]
Yes, good idea! Thank you 😀

**Comment by Yarflam** [comment]
I will do something better tomorrow. Explain how its works and move the files properly. (I had let a log file... my bad :/ )

**Comment by SpeederX** [comment]
> I will do something better tomorrow. Explain how its works and move the files properly. (I had let a log file... my bad :/ )

Don't worry, it's the first time i push something public and ask for a merge request =) and it's your own project. I was just looking for something to build neutralino and have a separated environment from the local dev i'm using

**Comment by Yarflam** [comment]
> Don't worry, it's the first time i push something public and ask for a merge request =) and it's your own project. I was just looking for something to build neutralino and have a separated environment from the local dev i'm using

Yes. Take my doubts ... were you able to test the script on your computer? I just realized that on Windows the relative path is not good and might not build with Docker Desktop for Windows. Especially since they are two different Dockerfiles: the first yarflam/neutralinojs-builder (available on Docker Hub) is used to encapsulate the Neutralinojs environment and the second to build a project by adding files & directories.

**Comment by Yarflam** [comment]
For your needs, you should go through the CI / CD of Gitlab. [Look at my snippet](https://gitlab.com/-/snippets/2107656).

**Comment by SpeederX** [comment]
> 
> 
> > Don't worry, it's the first time i push something public and ask for a merge request =) and it's your own project. I was just looking for something to build neutralino and have a separated environment from the local dev i'm using
> 
> Yes. Take my doubts ... were you able to test the script on your computer? I just realized that on Windows the relative path is not good and might not build with Docker Desktop for Windows. Especially since they are two different Dockerfiles: the first yarflam/neutralinojs-builder (available on Docker Hub) is used to encapsulate the Neutralinojs environment and the second to build a project by adding files & directories.

yea, i executed it directly via cmd so i could see the logs without the prompt to shutoff. It worked. I'm currently gonna use it these days i guess, have to pack some script i made with a webview, and i wanted to test it. I've a notebook with Kubuntu in which neutralino just works fine, but on win i had problems when running `neu build` and also the `listen` command. So i thought to build and docker and found yours )) thank you for making it.

**Comment by SpeederX** [comment]
> 
> 
> For your needs, you should go through the CI / CD of Gitlab. [Look at my snippet](https://gitlab.com/-/snippets/2107656).

gonna check that out next days, i've had a look to the compose, but i didn't use CI / CD of gitlab yet, even though at work i've seen them, didn't have the chance

**Pull request merged**
